### ISSUE TITLE
Conflict with version configuration key

### ISSUE THREAD

**Issue by Jamsek-m** [kumuluz/kumuluzee-version#2]
Currently service version (used in KumuluzEE Config & Discovery) is set using key 
```yaml
kumuluzee:
  version: 1.0.0
```
However this extension treats this key as object with its own configuration:
```yaml
kumuluzee:
  version:
    endpoint: /myCustomEndpoint
    file-path: test/MY_CUSTOM_.json
```
